spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_jwt_example?serverTimezone=Europe/Helsinki&useSSL=false
    username: executor
    password: executor
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  token:
    secret: weatherJwtKey
    expired: 86400000
    header:
      prefix: WeatherAuth_

cors:
  hosts:
    - "*"
    - "http://localhost:3000"