spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  token:
    secret: bearerSecretJwtKey
    expired: 86400000
    header:
      prefix: WeatherAuth_

cors:
  hosts:
    - "*"
    - "http://localhost:3000"