spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_jwt_example?serverTimezone=Europe/Helsinki&useSSL=false
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true

server:
  port: 80

jwt:
  token:
    secret: weatherJwtKey
    expired: 86400000
    header:
      prefix: WeatherAuth_

scheduling:
  cron:
    calculate-average-data: "0 0 0 * * *"
    generate-weather-data: "0 0 */4 * * *"
    subscription-check: "0 0 0 * * *"