CREATE TABLE IF NOT EXISTS registered_users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  subscription DATE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;